services:
  
  clickhouse:
    image: clickhouse/clickhouse-server:26.5
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
       - CLICKHOUSE_USER=logstore
       - CLICKHOUSE_PASSWORD=logstore
    restart: unless-stopped
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./deploy/clickhouse:/docker-entrypoint-initdb.d

  vector-aggregator:
    image: timberio/vector:0.56.0-alpine
    container_name: vector-aggregator
    volumes:
      - ./deploy/vector/aggregator.yaml:/etc/vector/vector.yaml:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8686/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: unless-stopped

  vector-agent:
    image: timberio/vector:0.56.0-alpine
    container_name: vector-agent
    volumes:
      - ./deploy/vector/agent.yaml:/etc/vector/vector.yaml:ro
      - logpipe_logs:/var/log/logpipe:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    depends_on:
      vector-aggregator:
        condition: service_healthy
    restart: unless-stopped

  crud-api:
    build:
      context: .
      dockerfile: deploy/crud-api/Dockerfile
    container_name: crud-api
    environment:
      - LOG_FILE=/var/log/logpipe/app.log
      - ADDR=:8080
    volumes:
      - logpipe_logs:/var/log/logpipe
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - logpipe_logs:/var/log/logpipe
    ports:
      - "8080:8080"
    depends_on:
      - crud-api
    restart: unless-stopped

volumes:
  clickhouse_data:
  logpipe_logs: