log_format json_http escape=json
    '{'
        '"timestamp":"$time_iso8601",'
        '"log_type":"http",'
        '"host":"$host",'
        '"method":"$request_method",'
        '"path":"$uri",'
        '"status":$status,'
        '"duration_ms":$request_time,'
        '"bytes":$body_bytes_sent,'
        '"client_ip":"$remote_addr",'
        '"user_agent":"$http_user_agent"'
    '}';

server {
    listen 8080;
    access_log /var/log/logpipe/access.log json_http;

    location / {
        proxy_pass http://crud-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
