sources:
  app_files:
    type: file
    include:
      - /var/log/logpipe/*.log
    read_from: beginning

sinks:
  to_aggregator:
    type: vector
    inputs: [app_files]
    address: vector-aggregator:6000